#!/usr/bin/env php
<?php declare(strict_types=1);

if (isset($GLOBALS['_composer_autoload_path'])) {
	define('PHPUNIT_COMPOSER_INSTALL', $GLOBALS['_composer_autoload_path']);

	unset($GLOBALS['_composer_autoload_path']);
} else {
	foreach ([
				 __DIR__ . '/../../autoload.php',
				 __DIR__ . '/../vendor/autoload.php',
				 __DIR__ . '/vendor/autoload.php',
			 ] as $file) {
		if (file_exists($file)) {
			define('PHPUNIT_COMPOSER_INSTALL', $file);

			break;
		}
	}

	unset($file);
}
require PHPUNIT_COMPOSER_INSTALL;

$filePath = $argv[1];
require $filePath;
print_r(get_declared_classes());
die;
$includedFiles = get_required_files();
$excludes = implode("|", [
	'\/vendor\/',
	'\/bootstrap.php$',
	'\/autoload.php$',
	'\/' . basename(__FILE__) . '$',
]);
$includedFiles = array_filter($includedFiles, function ($file) use ($excludes)
{
	return !preg_match("/$excludes/", $file);
});

echo json_encode($includedFiles);
